;
; This is ment to be included in the findApps_m.ahk program
;
  myDoNothingRightSide:
    return
  ;
  myRightSideJoy1:
  	processButton(controlerRightSide,1)
  	return
  ;
  myRightSideJoy2:
  	processButton(controlerRightSide,2)
  	return
  ;
  myRightSideJoy3:
  	processButton(controlerRightSide,3)
  	return
  ;
  myRightSideJoy4:
  	processButton(controlerRightSide,4)
  	return
  ;
  myRightSideJoy5:
  	processButton(controlerRightSide,5)
  	return
  ;
  myRightSideJoy6:
  	processButton(controlerRightSide,6)
  	return
  ;
  myRightSideJoy7:
  	processButton(controlerRightSide,7)
  	return
  ;
  myRightSideJoy8:
  	processButton(controlerRightSide,8)
  	return
  ;
  myRightSideJoy9:
  	processButton(controlerRightSide,9)
  	return
  ;
  myRightSideJoy10:
  	processButton(controlerRightSide,10)
  	return
  ;
  myRightSideJoy11:
  	processButton(controlerRightSide,11)
  	return
  ;
  myRightSideJoy12:
  	processButton(controlerRightSide,12)
  	return
  ;
  myRightSideJoy13:
  	processButton(controlerRightSide,13)
  	return
  ;
  myRightSideJoy14:
  	processButton(controlerRightSide,14)
  	return
  ;
  myRightSideJoy15:
  	processButton(controlerRightSide,15)
  	return
  ;
  myRightSideJoy16:
  	processButton(controlerRightSide,16)
  	return
  ;
  myRightSideJoy17:
  	processButton(controlerRightSide,17)
  	return
  ;
  myRightSideJoy18:
  	processButton(controlerRightSide,18)
  	return
  ;
  myRightSideJoy19:
  	processButton(controlerRightSide,19)
  	return
  ;
  myRightSideJoy20:
  	processButton(controlerRightSide,20)
  	return
  ;
  myRightSideJoy21:
  	processButton(controlerRightSide,21)
  	return
  ;
  myRightSideJoy22:
  	processButton(controlerRightSide,22)
  	return
  ;
  myRightSideJoy23:
  	processButton(controlerRightSide,23)
  	return
  ;
  myRightSideJoy24:
  	processButton(controlerRightSide,24)
  	return
  ;
  myRightSideJoy25:
  	processButton(controlerRightSide,25)
  	return
  ;
  myRightSideJoy26:
  	processButton(controlerRightSide,26)
  	return
  ;
  myRightSideJoy27:
  	processButton(controlerRightSide,27)
  	return
  ;
  myRightSideJoy28:
  	processButton(controlerRightSide,28)
  	return
  ;
  myRightSideJoy29:
  	processButton(controlerRightSide,29)
  	return
  ;
  myRightSideJoy30:
  	processButton(controlerRightSide,30)
  	return
  ;
  myRightSideJoy31:
  	processButton(controlerRightSide,31)
  	return
  ;
  myRightSideJoy32:
  	processButton(controlerRightSide,32)
  	return
  ;
